version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=utest
      - POSTGRES_PASSWORD=utest
      - POSTGRES_DB=kanalservice
    volumes:
      - flask_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app.py
    env_file:
      - creds/env.list
      - creds/env_tg.list
    depends_on:
      - db
volumes:
  flask_data: